In [6]:
# 1 ===========================================================
import sys
sys.path.append("/home/daniel/software/MEEN537/")
import kinematics as kin
from visualization import VizScene
import sympy as sp
import numpy as np
import time
np.set_printoptions(precision=4, suppress=True)


def getTau(q, F, arm):
    J = arm.jacob(q)[:3, :] # Only need the linear velocity components of the Jacobian
    print(f"\n Tau for q={q} is:")
    sp.pprint(J.T @ F)

# Define the arm
a1 = a2 = 1
dh = [[0, 0, a1, -np.pi/2.0],
      [0, 0, a2, 0]]
arm = kin.SerialArm(dh)


# Define different configurations and get tau
qa = [0, np.pi/4]
Fa = np.array([[-1], [0], [0]])
getTau(qa, Fa, arm)

qb = [0, np.pi/2]
Fb = np.array([[-1], [0], [0]])
getTau(qb, Fb, arm)

qc = [np.pi/4, np.pi/4]
Fc = np.array([[-1], [-1], [0]])
getTau(qc, Fc, arm)

qd = [0, 0]
Fd = np.array([[0], [0], [1]])
getTau(qd, Fd, arm)

qe = [0, 0]
Fe = np.array([[1], [0], [0]])
getTau(qe, Fe, arm)


 Tau for q=[0, 0.7853981633974483] is:
⎡4.32978028117747e-17⎤
⎢                    ⎥
⎣ 0.707106781186547  ⎦

 Tau for q=[0, 1.5707963267948966] is:
⎡6.12323399573677e-17⎤
⎢                    ⎥
⎣        1.0         ⎦

 Tau for q=[0.7853981633974483, 0.7853981633974483] is:
⎡-2.22044604925031e-16⎤
⎢                     ⎥
⎣         1.0         ⎦

 Tau for q=[0, 0] is:
⎡ 0  ⎤
⎢    ⎥
⎣-1.0⎦

 Tau for q=[0, 0] is:
⎡0⎤
⎢ ⎥
⎣0⎦


In [ ]:
# 2 ===========================================================
# Define the arm
dh = [[0, 0.2, 0, -np.pi/2.0],
      [0, 0, 0.2, 0],
      [np.pi/2, 0, 0, np.pi/2.0],
      [np.pi/2, 0.4, 0, -np.pi/2.0],
      [0, 0, 0, np.pi/2.0],
      [0, 0.4, 0, 0],]
arm = kin.SerialArm(dh)

viz = VizScene()
viz.add_arm(arm)
q = [np.pi/4,.3,.1,np.pi/2,np.pi/2,0]
viz.update(qs = [q])

goal = [0.1, 0.1, 0.1] 
viz.add_marker(arm.fk(q)[:3,-1])
viz.hold()


In [ ]:
# 3a ===========================================================

# Define the arm
dh = [[0, 0.2, 0, -np.pi/2.0],
      [0, 0, 0.2, 0],
      [np.pi/2, 0, 0, np.pi/2.0],
      [np.pi/2, 0.4, 0, -np.pi/2.0],
      [0, 0, 0, np.pi/2.0],
      [0, 0.4, 0, 0],]
jt_types = ['r', 'r', 'r', 'r', 'r', 'r']
arm = kin.SerialArm(dh, jt=jt_types)

q1 = [0, 0, 0, 0, 0, 0]
q2 = [np.pi/4, np.pi/4, np.pi/4, np.pi/4, np.pi/4, np.pi/4]

d1 = [-.149, .364, 1.03]
d2 = [-.171, -.682, -.192]
d3 = [.822, -.1878, .533]
d4 = [-.336, .095, .931]
d5 = [.335, .368, .88]
d = [d1, d2, d3, d4, d5]

# starting from q1 Jacobian Transpose method
# for goal in d:
#       q_goal, error, count, _, _ = arm.ik_position(goal, q1, 'J_T', K=np.eye(3))
#       #     print(f"Final q values={q_goal}, \nwith an error of {error}, \nfor position={goal}")
#       print(error, count)
# print()

# # starting from q2 Jacobian Transpose method
# for goal in d:
#       q_goal, error, count, _, _ = arm.ik_position(goal, q2, 'J_T', K=np.eye(3))
#       # print(f"Final q values={q_goal}, \nwith an error of {error}, \nfor position={goal}")
#       print(error, count)
# print()

# starting from q1 pinv method
for goal in d:
      q_goal, error, count, _, _ = arm.ik_position(goal, q1, 'pinv', K=np.eye(3))
      #     print(f"Final q values={q_goal}, \nwith an error of {error}, \nfor position={goal}")
      print(error, count)      
print()

# starting from q2 pinv method
for goal in d:
      q_goal, error, count, _, _ = arm.ik_position(goal, q2, 'pinv', K=np.eye(3))
      #     print(f"Final q values={q_goal}, \nwith an error of {error}, \nfor position={goal}")
      print(error, count)
print()

# Plot Final Solution configuration for one target
# q_goal, error, _, _, _ = arm.ik_position(d1, q1, 'pinv', K=np.eye(3)*.1, max_iter=1000)
# q_goal, error, _, _, _ = arm.ik_position(d1, q1, 'J_T', K=np.eye(3)*10, max_iter=1000)

# viz.add_marker(d1)
# viz.update(qs = [q_goal])
# viz.hold()

[-0.      0.0007  0.0002] 11
[-0.0003 -0.0014 -0.0004] 17
[ 0.0024  0.0004 -0.0012] 7
[-0.0002  0.0001  0.0001] 11
[ 0.0015 -0.002   0.0042] 6

[-0.0001  0.0003  0.0004] 23
[-0.0009 -0.004   0.0006] 14
[ 0.0002 -0.0001  0.    ] 7
[-0.0006  0.0002  0.    ] 6
[0.0028 0.0006 0.0038] 7

