In [2]:
import numpy as np

Jv1 = np.array([[0,0,1],
                [0,0,0],
                [0,0,0]])

Jv2 = np.array([[0,0,1],
                [0,1,0],
                [0,0,0]])

Jv3 = np.array([[0,0,1],
                [0,1,0],
                [0,0,1]])

print(Jv1.T@Jv1)
print(Jv2.T@Jv2)
print(Jv3.T@Jv3)

[[0 0 0]
 [0 0 0]
 [0 0 1]]
[[0 0 0]
 [0 1 0]
 [0 0 1]]
[[0 0 0]
 [0 1 0]
 [0 0 2]]
