In [20]:
# 2 (b) ===========================================================
import sys
sys.path.append("C:/Users/danie/Documents/School/MEEN537/HW")
sys.path.append("/home/daniel/Documents/MEEN537/HW/")
import kinematics as kin
import transforms as tr
import numpy as np
np.set_printoptions(precision=4, suppress=True)


L1 = 0.69
L2 = .36435
L3 = 0.69
L4 = .37429
L5 = .01
L6 = .3683

# dh = [[0, 0, 0, 0],            # s0
#       [np.pi/2.0, 0, L1, -np.pi/2],           # s1
#       [0, L2, 0, np.pi/2.0],      # e0
#       [0, 0, L3, -np.pi/2.0],          # e1
      
#       [0, L4, 0, np.pi/2.0],  # w0
#       [0, 0, L5, -np.pi/2.0],                 # w1
#       [0, 0, 0, np.pi/2]]                     # w2

dh = [[0, .27035, 0, -np.pi/2.0],           # s0
      [np.pi/2.0, 0, 0, np.pi/2],           # s1
      [0, .069+.36435, 0, -np.pi/2.0],      # e0
      [-np.pi/2, 0, 0, np.pi/2.0],          # e1
      [0, .37442+.069, -0.01, -np.pi/2.0],  # w0
      [0, 0, 0, np.pi/2.0],                 # w1
      [0, .2295, 0, 0]]                     # w2

dh = [[0, .27035, 0.069, np.pi/2.0],           # s0
      [np.pi/2.0, 0, 0, np.pi/2],           # s1
      [0, .36435, -0.069, -np.pi/2.0],      # e0
      [-np.pi/2, 0, 0, np.pi/2.0],          # e1
      [0, .37442, -0.01, -np.pi/2.0],  # w0
      [0, 0, 0, np.pi/2.0],                 # w1
      [0, .2295, 0, 0]]                     # w2

jt_types = ['r', 'r', 'r', 'r', 'r', 'r', 'r']
base = tr.se3(tr.rotz(-np.pi/4), np.array([0.06353, -.2597, .119]))
arm = kin.SerialArm(dh, jt=jt_types, base=base)

# defining two different sets of joint angles
q_set1 = [0.49816026, -1.19113608,  0.1434272,   0.02109224, -2.38994207,  0.09894176, 2.15102456]
q_set2 = [0.72902437, -0.36815539,  0.09779128,  0.40612141, -2.37191779,  0.05023787, 2.08621387]
q_set3 = [0.62087872, -1.00168945,  0.10814565,  1.51403904, -1.91325754, -1.56926235,  2.86317514]
q_set4 = [1.18461666, -0.76775738,  0.11850002,  0.54417968, -2.83863145, -1.01050984,  3.0422674 ]

print(f"position 1: \n {arm.fk(q_set1, base=True)}")
print()
print(f"position 2: \n {arm.fk(q_set2, base=True)}")
print()
print(f"position 3: \n {arm.fk(q_set3, base=True)}")
print()
print(f"position 4: \n {arm.fk(q_set4, base=True)}")


position 1: 
 [[ 0.4139 -0.3767 -0.8288 -0.3011]
 [ 0.1289 -0.877   0.4629 -0.0429]
 [-0.9012 -0.2984 -0.3144 -0.1982]
 [ 0.      0.      0.      1.    ]]

position 2: 
 [[ 0.9809  0.1941  0.0118  0.4734]
 [ 0.1912 -0.9735  0.1253 -0.2208]
 [ 0.0358 -0.1206 -0.9921 -0.4065]
 [ 0.      0.      0.      1.    ]]

position 3: 
 [[-0.2261 -0.9731  0.0441  0.4616]
 [ 0.0948 -0.067  -0.9932 -0.552 ]
 [ 0.9695 -0.2204  0.1074 -0.2551]
 [ 0.      0.      0.      1.    ]]

position 4: 
 [[ 0.7132  0.0929  0.6948  0.401 ]
 [ 0.1048 -0.9942  0.0254 -0.1327]
 [ 0.6931  0.0547 -0.7188 -0.4438]
 [ 0.      0.      0.      1.    ]]


In [ ]:
# print("First Position, J is:")
# print(J1)
# print("Second Position, J is:")
# print(J2)
# print("Third Position, J is:")
# print(J3)
# print("Fourth Position, J is:")
# print(J4)


# calculating two different jacobians for the two different joint configurations. 
# J1 = arm.jacob(q_set1)
# J2 = arm.jacob(q_set2)
# J3 = arm.jacob(q_set3)
# J4 = arm.jacob(q_set4)